# Generated by Django 5.0.6 on 2024-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE')], max_length=20)),
            ],
        ),
    ]
