# Generated by Django 5.0.6 on 2024-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
