# Generated by Django 5.0.6 on 2024-07-06 13:27

import semanticapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanticapp', '0002_employee_position_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='img/', validators=[semanticapp.validators.validate_image_size]),
        ),
    ]
