# Generated by Django 5.0.6 on 2024-07-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanticapp', '0003_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
